version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:3000